server:
  port: 8092

spring:
  application:
    name: auth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/auth
    username: "postgres"
    password: "postgres"
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    org:
      springframework:
        security: TRACE

